---
# main task file
#
- name: ensure jail.conf contains jail stanza
  blockinfile:
    dest: /etc/jail.conf
    create: yes
    marker: "# {mark} Jail {{ jail_name }}"
    content: |
      {{ jail_name }} {
        host.hostname = {{ hostname }};
      {% if extra_opts is defined %}{% for opt in extra_opts %}  {{ opt.name }}{% if opt.option is defined %} = {{ opt.option }}{% endif %};
      {% endfor %}
      {% endif %}
      }

- name: ensure jail dataset
  include_role:
    name: bvansomeren.zfs
    tasks_from: dataset
  vars:
    zfs_dataset:
      parents: "{{ jail_dataset }}"
      name: "{{ jail_name }}"
      extra_zfs_properties: "{{ extra_zfs_properties }}"

- name: ensure base FreeBSD install
  command: tar -xf "{{ jail_freebsd_download }}/{{ item.file }}" -C "{{ jail_mountpoint }}"
  args:
    creates: "{{ jail_mountpoint }}/{{ item.creates }}"
  with_items: " {{ jail_default_install }}"
  register: freebsd_installed_in_jail

- name: ensure minimal configuration is in template
  copy:
    remote_src: yes
    src: "/{{ item }}"
    dest: "{{ jail_mountpoint }}/{{ item }}"
    force: no
  with_items: "{{ jail_minimal_conf }}"

- name: create optional zfs mounts
  include_role:
    name: bvansomeren.zfs
    tasks_from: dataset
  vars:
    zfs_dataset:
      name: "{{ item.name }}"
      extra_zfs_properties: "{{ item.extra_zfs_properties }}"
      parents: "{{ jail_dataset }}/{{ jail_name }}"
  with_items: "{{ jail_zfs_mounts }}"

- name: optionally ensure jail receive further rc.conf changes
  command: sysrc -f {{ jail_mountpoint }}/etc/rc.conf {% for rc in jail_rc_defaults %} {{rc.name}}={{rc.value}}{% endfor %} creates={{ jail_mountpoint }}/etc/rc.conf

- name: ensure jail rc.conf hostname using sysrc
  command: sysrc -f {{ jail_mountpoint }}/etc/rc.conf hostname={{ hostname }}
  register: sysrc_changed
  changed_when:  "'{{ hostname }} -> {{ hostname }}' not in sysrc_changed.stdout"

- name: ensure jail nat /etc/pf/anchor_nat_jail.{{ jail_name }}.conf
  template:
    src: pf.anchor.nat-jail.conf.j2
    dest: /etc/pf/anchor_nat_jail.{{ jail_name }}.conf
  notify:
  - Reload PF

- name: Add nat anchor to configuration
  lineinfile:
    dest: /etc/pf/anchor_nat_jails.conf
    state: present
    line: 'include "/etc/pf/anchor_nat_jail.{{ jail_name }}.conf"'
  notify:
  - Reload PF

- name: ensure jail nat /etc/pf/anchor_rdr_jail.{{ jail_name }}.conf
  template:
    src: pf.anchor.rdr-jail.conf.j2
    dest: /etc/pf/anchor_rdr_jail.{{ jail_name }}.conf
  when: rdr_ports is defined
  notify:
  - Reload PF

- name: Add rdr anchor to configuration
  lineinfile:
    dest: /etc/pf/anchor_rdr_jails.conf
    state: present
    line: 'include "/etc/pf/anchor_rdr_jail.{{ jail_name }}.conf"'
  when: rdr_ports is defined
  notify:
  - Reload PF

- name: force PF reload so that NAT works on install
  meta: flush_handlers
  when: freebsd_installed_in_jail|changed

- name: ensure jail is started
  command: jail -cm {{ jail_name }}

- name: ensure default packages are installed
  pkgng:
    name: "{{ default_packages }}"
    jail: "{{ jail_name }}"
    state: present

- name: ensure extra packages are installed
  pkgng:
    name: "{{ packages }}"
    jail: "{{ jail_name }}"
    state: present

- name: ensure services are enabled in jail
  command: jexec {{ jail_name }} sysrc {{ item }}_enable="YES"
  with_items: "{{ services }}"

- name: ensure services are started inside the jail
  service:
    name: "{{ item }}"
    state: started
    args: "-j {{ jail_name }}"
  with_items: "{{ services }}"

- include_tasks: users.yml
  vars:
    jail_user: "{{ item }}"
  with_items: "{{ users }}"

- name: ensure wheel group in sudoers without password
  blockinfile:
    dest: "{{ jail_mountpoint }}/usr/local/etc/sudoers.d/wheel"
    create: yes
    content: |
      %wheel ALL=(ALL) NOPASSWD: ALL

- name: execute secondary roles
  include_role:
    name: "{{ item }}"
  with_items: "{{ jail_roles }}"
