---
# users.yml
#
- debug:
    msg: "creating user: {{ jail_user }}"

- name: ensure user is created
  command: chroot {{ jail_mountpoint }} pw useradd {{ jail_user.name }} {% if jail_user.group is defined %} -g {{ jail_user.group }}{% endif %} {% if jail_user.sudo %} -G wheel {% endif %} -s {{ jail_user.shell | default('/bin/sh') }} -w no -m 
  args:
    creates: "{{ jail_mountpoint }}/home/{{ jail_user.name }}"

- name: get the correct uid for user files
  command: jexec -U {{ jail_user.name }} {{ jail_name }} id -u
  register: uid

- name: get the correct gid for user files
  command: jexec -U {{ jail_user.name }} {{ jail_name }} id -g
  register: gid

- name: ensure ssh folder is setup if user is defined
  file:
    path: "{{ jail_mountpoint }}/home/{{ jail_user.name }}/.ssh/"
    state: directory
    owner: "{{ uid.stdout }}"
    group: "{{ gid.stdout }}" 
  when: 'jail_user.ssh | default(no)'

- name: ensure key is placed in authorized_keys if presented
  copy:
    src: "{{ jail_user.name}}.pub"
    dest: "{{ jail_mountpoint }}/home/{{ jail_user.name }}/.ssh/authorized_keys"
    owner: "{{ uid.stdout }}"
    group: "{{ gid.stdout }}"
    mode: 0600
  when: 'jail_user.ssh | default(no)'
